# Generated by Django 3.1.5 on 2021-02-02 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20210202_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('in_process', 'in_process'), ('not_delivered', 'not_delivered'), ('delivered', 'delivered')], default='in_process', max_length=40),
        ),
    ]
