# Generated by Django 3.1.5 on 2021-02-12 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20210212_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('Nal', 'Nal'), ('Wall', 'Wall')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
